#!/bin/sh

PORTABLE_HOME="${APPIMAGE}.home"

mkdir -p "$PORTABLE_HOME/.config"

# Si no existe el enlace en el HOME real, créalo
if [ ! -e "$HOME/.config/Subtitle Edit" ]; then
    ln -s "$PORTABLE_HOME/.config/Subtitle Edit" \
          "$HOME/.config/Subtitle Edit"
fi

mkdir -p "$PORTABLE_HOME/.config/Subtitle Edit"

exec "$APPDIR/SubtitleEdit" "$@"
